services:
  symfony:
    image: jurihahn/symfony-dev:latest
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - SYMFONY_SERVER_PORT=${SYMFONY_SERVER_PORT}
    ports:
      - "${SYMFONY_SERVER_PORT}:8000"
      - "${SYMFONY_PROXY_PORT}:7080"
    volumes:
      - ./app:/var/www/${PROJECT_NAME}

  db:
    image: mariadb
    container_name: db_${PROJECT_NAME}
    volumes:
      - ./mariadb/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_${PROJECT_NAME}
    environment:
      - PMA_HOSTS=db_${PROJECT_NAME}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
