services:
  symfony:
    image: jurihahn/symfony-dev:latest
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - "8000:8000"
      - "7080:7080"
    volumes:
      - ./app:/var/www/${PROJECT_NAME}
